daemon off;
user root;
worker_processes 1;
pid /run/nginx/nginx.pid;
error_log stderr notice;

events {
    worker_connections 128;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    access_log    /dev/stdout;
    error_log     stderr notice;

    sendfile      on;
    keepalive_timeout 65;

    server {
        listen __PORT__;

        root /app/www;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
